In [1]:
import pandas as pd

In [2]:
# Read the file by giving the path of the dataset present inside the file explorer.
file_path = r"C:\Users\HP\Downloads\archive\movies-db-1_dataset.xlsx"

In [3]:
# Store the values present inside the different sheets in a particular variable.
movies = pd.read_excel(file_path, sheet_name = "movies")
financials = pd.read_excel(file_path, sheet_name = "financials")
actors = pd.read_excel(file_path, sheet_name = "actors")
movie_actor = pd.read_excel(file_path, sheet_name = "movie_actor")
languages = pd.read_excel(file_path, sheet_name = "languages")

In [4]:
# Show the top 5 rows present inside the dataset.
movies.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [5]:
type(movies)

pandas.core.frame.DataFrame

In [6]:
# Show the no. of rows and columns
movies.shape

(39, 7)

In [7]:
# Show column names
movies.columns

Index(['movie_id', 'title', 'industry', 'release_year', 'imdb_rating',
       'studio', 'language_id'],
      dtype='object')

In [8]:
movies.dtypes

movie_id          int64
title            object
industry         object
release_year      int64
imdb_rating     float64
studio           object
language_id       int64
dtype: object

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      39 non-null     int64
 1   title         39 non-null     object
 2   industry      39 non-null     object
 3   release_year  39 non-null     int64
 4   imdb_rating   38 non-null     float64
 5   studio        36 non-null     object
 6   language_id   39 non-null     int64
dtypes: float64(1), int64(3), object(3)
memory usage: 2.3+ KB

In [10]:
# Show the aggregate functions by using numbrical columns.
movies.describe()

         movie_id  release_year  imdb_rating  language_id
count   39.000000     39.000000    38.000000    39.000000
mean   120.666667   2006.282051     7.947368     3.435897
std     11.795033     17.945750     1.180869     1.970772
min    101.000000   1946.000000     1.900000     1.000000
25%    110.500000   2000.500000     7.825000     1.000000
50%    121.000000   2013.000000     8.100000     5.000000
75%    130.500000   2018.000000     8.400000     5.000000
max    140.000000   2022.000000     9.300000     7.000000

In [11]:
movies.describe(include = "object")

                   title   industry          studio
count                 39         39              36
unique                39          2              22
top     K.G.F: Chapter 2  Hollywood  Marvel Studios
freq                   1         21               8

In [12]:
movies["title"].head()

0                               K.G.F: Chapter 2
1    Doctor Strange in the Multiverse of Madness
2                          Thor: The Dark World
3                                Thor: Ragnarok
4                        Thor: Love and Thunder
Name: title, dtype: object

In [13]:
movies[["title","release_year"]].head()

                                         title  release_year
0                             K.G.F: Chapter 2          2022
1  Doctor Strange in the Multiverse of Madness          2022
2                        Thor: The Dark World           2013
3                              Thor: Ragnarok           2017
4                      Thor: Love and Thunder           2022

In [14]:
movies.loc[0]  #access with using index

movie_id                     101
title           K.G.F: Chapter 2
industry               Bollywood
release_year                2022
imdb_rating                  8.4
studio             Hombale Films
language_id                    3
Name: 0, dtype: object

In [15]:
movies.loc[0:4]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [16]:
movies.loc[0:4 , ["title" , "studio"]]  # access the perticular column by using indexing

                                         title          studio
0                             K.G.F: Chapter 2   Hombale Films
1  Doctor Strange in the Multiverse of Madness  Marvel Studios
2                        Thor: The Dark World   Marvel Studios
3                              Thor: Ragnarok   Marvel Studios
4                      Thor: Love and Thunder   Marvel Studios

In [17]:
movies.loc[movies["imdb_rating"] > 8]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
5,106,Sholay,Bollywood,1975,8.1,United Producers,1
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
21,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
25,127,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,7
26,128,Taare Zameen Par,Bollywood,2007,8.3,NaN,1
27,129,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,1
28,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
34,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [18]:
movies.loc[:, "title"].head()  #access only one col

0                               K.G.F: Chapter 2
1    Doctor Strange in the Multiverse of Madness
2                          Thor: The Dark World
3                                Thor: Ragnarok
4                        Thor: Love and Thunder
Name: title, dtype: object

In [19]:
movies.iloc[0]

movie_id                     101
title           K.G.F: Chapter 2
industry               Bollywood
release_year                2022
imdb_rating                  8.4
studio             Hombale Films
language_id                    3
Name: 0, dtype: object

In [20]:
movies.iloc[0:4]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5

In [21]:
movies.iloc[0:4,0:3]

   movie_id                                        title   industry
0       101                             K.G.F: Chapter 2  Bollywood
1       102  Doctor Strange in the Multiverse of Madness  Hollywood
2       103                        Thor: The Dark World   Hollywood
3       104                              Thor: Ragnarok   Hollywood

In [22]:
movies.iloc[:,1].head()

0                               K.G.F: Chapter 2
1    Doctor Strange in the Multiverse of Madness
2                          Thor: The Dark World
3                                Thor: Ragnarok
4                        Thor: Love and Thunder
Name: title, dtype: object

In [23]:
movies[movies["industry"] == "Hollywood"].head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5

In [24]:
movies[movies["release_year"] > 2020]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
30,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2
31,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [25]:
movies[(movies["industry"] == "Hollywood") & (movies["imdb_rating"]>8)].head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5

In [26]:
movies[(movies["industry"] == "Hollywood") | (movies["imdb_rating"]>8)].head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [27]:
# match the condition with columns values 
movies[movies["studio"].isin(["Marvel Studios","Zee Studios"])]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5
36,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5

In [28]:
movies[movies["release_year"].between(2018,2022)]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
29,131,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1
30,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2
31,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [29]:
movies.sort_values("imdb_rating", ascending = False).head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5

In [30]:
movies.sort_values(["title","imdb_rating"], ascending = [True, False]).head(8)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1
17,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
32,134,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,2
9,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1
34,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5

In [31]:
movies["rating_category"] = movies["imdb_rating"].apply(lambda x : "Excellent" if x > 8 else "Normal")

In [32]:
movies.head(3)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,rating_category
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,Excellent
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,Normal
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,Normal

In [33]:
movies["movie_age"] = 2026 - movies["release_year"]

In [34]:
movies.head(3)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,rating_category,movie_age
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,Excellent,4
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,Normal,13

In [35]:
movies.columns

Index(['movie_id', 'title', 'industry', 'release_year', 'imdb_rating',
       'studio', 'language_id', 'rating_category', 'movie_age'],
      dtype='object')

In [36]:
movies.rename(columns = {
    "release_year": "year",
    "imdb_rating": "rating"
}, inplace = True)           #inplace is used to make the changes in original without using assignment operator

In [37]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,Excellent,4
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4

In [38]:
movies.drop(columns = ["language_id"]).head()

,movie_id,title,industry,year,rating,studio,rating_category,movie_age
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,Excellent,4
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,Normal,4
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,Normal,13
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,Normal,9
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,Normal,4

In [39]:
movies.drop(index = 0, inplace = True)

In [40]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,Sholay,Bollywood,1975,8.1,United Producers,1,Excellent,51

In [41]:
movies.isna().sum()

movie_id           0
title              0
industry           0
year               0
rating             1
studio             3
language_id        0
rating_category    0
movie_age          0
dtype: int64

In [42]:
movies.isnull().sum()

movie_id           0
title              0
industry           0
year               0
rating             1
studio             3
language_id        0
rating_category    0
movie_age          0
dtype: int64

In [43]:
movies["rating"].fillna(movies["rating"].mean(),inplace = True)

C:\Users\HP\AppData\Local\Temp\ipykernel_11092\1781443015.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies["rating"].fillna(movies["rating"].mean(),inplace = True)

In [44]:
movies["studio"].fillna("Unknown",inplace = True)

C:\Users\HP\AppData\Local\Temp\ipykernel_11092\1494411986.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies["studio"].fillna("Unknown",inplace = True)

In [45]:
movies.isnull().sum()

movie_id           0
title              0
industry           0
year               0
rating             0
studio             0
language_id        0
rating_category    0
movie_age          0
dtype: int64

In [46]:
movies.duplicated().sum()

np.int64(0)

In [47]:
movies.drop_duplicates(inplace = True)

In [48]:
movies["title"] = movies["title"].str.upper()

In [49]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,THOR: THE DARK WORLD,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,THOR: RAGNAROK,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,THOR: LOVE AND THUNDER,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,SHOLAY,Bollywood,1975,8.1,United Producers,1,Excellent,51

In [50]:
movies["title"].str.len().head()

1    43
2    21
3    15
4    23
5     6
Name: title, dtype: int64

In [51]:
movies[movies["title"].str.contains("Thor", case = False)]

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
2,103,THOR: THE DARK WORLD,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,THOR: RAGNAROK,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,THOR: LOVE AND THUNDER,Hollywood,2022,6.8,Marvel Studios,5,Normal,4

In [52]:
movies["title"].str.strip().head()

1    DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS
2                           THOR: THE DARK WORLD
3                                 THOR: RAGNAROK
4                         THOR: LOVE AND THUNDER
5                                         SHOLAY
Name: title, dtype: object

In [53]:
movies.groupby("industry")["rating"].mean()

industry
Bollywood    7.655008
Hollywood    8.161905
Name: rating, dtype: float64

In [54]:
movies.groupby("industry")["rating"].agg(["max","min","mean","count"])

           max  min      mean  count
industry
Bollywood  8.4  1.9  7.655008     17
Hollywood  9.3  6.8  8.161905     21

In [55]:
movies.groupby("industry").agg({
    "rating" : ["max","min"],
    "movie_id" : "count",
    "rating_category" : ["min","max"]})

          rating      movie_id rating_category
             max  min    count             min     max
industry
Bollywood    8.4  1.9       17       Excellent  Normal
Hollywood    9.3  6.8       21       Excellent  Normal

In [56]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,THOR: THE DARK WORLD,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,THOR: RAGNAROK,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,THOR: LOVE AND THUNDER,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,SHOLAY,Bollywood,1975,8.1,United Producers,1,Excellent,51

In [57]:
financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [58]:
financials.shape

(40, 5)

In [59]:
movies.shape

(38, 9)

In [60]:
movies_financials = pd.merge(movies,financials, on = "movie_id", how = "inner")

In [61]:
movies_financials.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age,budget,revenue,unit,currency
0,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022,7.0,Marvel Studios,5,Normal,4,200.0,954.8,Millions,USD
1,103,THOR: THE DARK WORLD,Hollywood,2013,6.8,Marvel Studios,5,Normal,13,165.0,644.8,Millions,USD
2,104,THOR: RAGNAROK,Hollywood,2017,7.9,Marvel Studios,5,Normal,9,180.0,854.0,Millions,USD
3,105,THOR: LOVE AND THUNDER,Hollywood,2022,6.8,Marvel Studios,5,Normal,4,250.0,670.0,Millions,USD
4,107,DILWALE DULHANIA LE JAYENGE,Bollywood,1995,8.0,Yash Raj Films,1,Normal,31,400.0,2000.0,Millions,INR

In [62]:
movies_financials.shape

(36, 13)

In [63]:
languages.shape

(8, 2)

In [64]:
languages.columns

Index(['language_id', 'name'], dtype='object')

In [65]:
movies.columns

Index(['movie_id', 'title', 'industry', 'year', 'rating', 'studio',
       'language_id', 'rating_category', 'movie_age'],
      dtype='object')

In [66]:
movies_data = pd.merge(movies_financials, languages, on = "language_id", how = "left")

In [67]:
movies_data.sample(4)

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age,budget,revenue,unit,currency,name
16,121,THE DARK KNIGHT,Hollywood,2008,9.0,Syncopy,5,Excellent,18,185.0,1006.0,Millions,USD,English
10,115,THE PURSUIT OF HAPPYNESS,Hollywood,2006,8.0,Columbia Pictures,5,Normal,20,55.0,307.1,Millions,USD,English
3,105,THOR: LOVE AND THUNDER,Hollywood,2022,6.8,Marvel Studios,5,Normal,4,250.0,670.0,Millions,USD,English
4,107,DILWALE DULHANIA LE JAYENGE,Bollywood,1995,8.0,Yash Raj Films,1,Normal,31,400.0,2000.0,Millions,INR,Hindi

In [68]:
movies_data.columns = movies_data.columns.str.replace("name" , "language")

In [69]:
movies_data.sample(3)

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age,budget,revenue,unit,currency,language
13,118,IT'S A WONDERFUL LIFE,Hollywood,1946,8.6,Liberty Films,5,Excellent,80,3.18,3.3,Millions,USD,English
9,113,INTERSTELLAR,Hollywood,2014,8.6,Warner Bros. Pictures,5,Excellent,12,165.00,701.8,Millions,USD,English
25,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1,Excellent,12,850.00,8540.0,Millions,INR,Hindi

In [70]:
movies_data["revenue_millions"] = movies_data.apply(
    lambda row :
    row["revenue"] *1000
    if row["unit"]=="Billions"
    else row["revenue"],
    axis = 1
)

In [71]:
movies_data["budget_millions"] = movies_data.apply(
    lambda row :
    row["budget"] *1000
    if row["unit"]=="Billions"
    else row["budget"],
    axis = 1
)

In [72]:
movies_data["unit"].value_counts()

unit
Millions     29
Billions      6
Thousands     1
Name: count, dtype: int64

In [73]:
movies_data["profit_millions"] = movies_data["revenue_millions"] - movies_data["budget_millions"]

In [74]:
movies_data.head(3)

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age,budget,revenue,unit,currency,language,revenue_millions,budget_millions,profit_millions
0,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022,7.0,Marvel Studios,5,Normal,4,200.0,954.8,Millions,USD,English,954.8,200.0,754.8
1,103,THOR: THE DARK WORLD,Hollywood,2013,6.8,Marvel Studios,5,Normal,13,165.0,644.8,Millions,USD,English,644.8,165.0,479.8
2,104,THOR: RAGNAROK,Hollywood,2017,7.9,Marvel Studios,5,Normal,9,180.0,854.0,Millions,USD,English,854.0,180.0,674.0

In [75]:
industry_map = {                         #"map" is used to change the name of the column
    "Hollywood" : "International",
    "Bollywood" : "Indian"
}

In [76]:
movies_data["industry_type"] = movies_data["industry"].map(industry_map)

In [77]:
movies_data.sample(4)

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age,budget,revenue,unit,currency,language,revenue_millions,budget_millions,profit_millions,industry_type
28,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2,Normal,4,5.5,12.0,Billions,INR,Telugu,12000.0,5500.0,6500.0,Indian
34,139,RACE 3,Bollywood,2018,1.9,Salman Khan Films,1,Normal,8,1.8,3.1,Billions,INR,Hindi,3100.0,1800.0,1300.0,Indian
29,134,BAAHUBALI: THE BEGINNING,Bollywood,2015,8.0,Arka Media Works,2,Normal,11,1.8,6.5,Billions,INR,Telugu,6500.0,1800.0,4700.0,Indian
23,128,TAARE ZAMEEN PAR,Bollywood,2007,8.3,Unknown,1,Excellent,19,120.0,1350.0,Millions,INR,Hindi,1350.0,120.0,1230.0,Indian

In [78]:
pd.pivot_table(movies_data, index = "year", columns = "industry", values = "rating", aggfunc = "mean")

industry  Bollywood  Hollywood
year
1946            NaN       8.60
1955       8.300000        NaN
1972            NaN       9.20
1993            NaN       8.60
1994            NaN       9.30
1995       8.000000        NaN
1997            NaN       7.90
2000            NaN       8.50
2001       7.400000        NaN
2003       8.100000        NaN
2006            NaN       8.00
2007       8.300000        NaN
2008            NaN       9.00
2009       8.400000       7.80
2011            NaN       6.90
2013            NaN       6.80
2014       8.100000       8.20
2015       7.766667        NaN
2017            NaN       7.90
2018       4.917568       8.40
2019            NaN       8.45
2021       8.000000        NaN
2022       8.150000       6.90

In [79]:
pd.pivot_table(movies_data, index = "year", values = "profit_millions", aggfunc = "sum")

      profit_millions
year
1946             0.12
1955         30000.00
1972           283.80
1993          1283.20
1994            48.30
1995          1600.00
1997          2002.00
2000           357.50
2001           970.00
2003           310.00
2006           252.10
2007          1230.00
2008           821.00
2009          6060.00
2011           153.90
2013           479.80
2014          8764.20
2015         17590.00
2017           674.00
2018          7848.00
2019          2645.60
2021          2050.00
2022         10833.80

In [80]:
pd.crosstab(
    movies_data["industry"],
    movies_data["language"]
)

language   Bengali  English  Hindi  Telugu
industry
Bollywood        1        0     12       3
Hollywood        0       20      0       0

In [81]:
pd.crosstab(
    movies_data["language"],
    movies_data["industry"]
)

industry  Bollywood  Hollywood
language
Bengali           1          0
English           0         20
Hindi            12          0
Telugu            3          0

In [82]:
df1 = movies.iloc[:10]

In [83]:
df2 = movies.iloc[10:20]

In [84]:
df1.shape

(10, 9)

In [85]:
df2.shape

(10, 9)

In [86]:
df2

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
11,112,INCEPTION,Hollywood,2010,8.8,Warner Bros. Pictures,5,Excellent,16
12,113,INTERSTELLAR,Hollywood,2014,8.6,Warner Bros. Pictures,5,Excellent,12
13,115,THE PURSUIT OF HAPPYNESS,Hollywood,2006,8.0,Columbia Pictures,5,Normal,20
14,116,GLADIATOR,Hollywood,2000,8.5,Universal Pictures,5,Excellent,26
15,117,TITANIC,Hollywood,1997,7.9,Paramount Pictures,5,Normal,29
16,118,IT'S A WONDERFUL LIFE,Hollywood,1946,8.6,Liberty Films,5,Excellent,80
17,119,AVATAR,Hollywood,2009,7.8,20th Century Fox,5,Normal,17
18,120,THE GODFATHER,Hollywood,1972,9.2,Paramount Pictures,5,Excellent,54
19,121,THE DARK KNIGHT,Hollywood,2008,9.0,Syncopy,5,Excellent,18
20,122,SCHINDLER'S LIST,Hollywood,1993,9.0,Universal Pictures,5,Excellent,33

In [87]:
pd.concat([df1,df2])  #add table vertically/row vise

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,THOR: THE DARK WORLD,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,THOR: RAGNAROK,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,THOR: LOVE AND THUNDER,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,SHOLAY,Bollywood,1975,8.1,United Producers,1,Excellent,51
6,107,DILWALE DULHANIA LE JAYENGE,Bollywood,1995,8.0,Yash Raj Films,1,Normal,31
7,108,3 IDIOTS,Bollywood,2009,8.4,Vinod Chopra Films,1,Excellent,17
8,109,KABHI KHUSHI KABHIE GHAM,Bollywood,2001,7.4,Dharma Productions,1,Normal,25
9,110,BAJIRAO MASTANI,Bollywood,2015,7.2,Unknown,1,Normal,11
10,111,THE SHAWSHANK REDEMPTION,Hollywood,1994,9.3,Castle Rock Entertainment,5,Excellent,32
11,112,INCEPTION,Hollywood,2010,8.8,Warner Bros. Pictures,5,Excellent,16
12,113,INTERSTELLAR,Hollywood,2014,8.6,Warner Bros. Pictures,5,Excellent,12
13,115,THE PURSUIT OF HAPPYNESS,Hollywood,2006,8.0,Columbia Pictures,5,Normal,20
14,116,GLADIATOR,Hollywood,2000,8.5,Universal Pictures,5,Excellent,26
15,117,TITANIC,Hollywood,1997,7.9,Paramount Pictures,5,Normal,29
16,118,IT'S A WONDERFUL LIFE,Hollywood,1946,8.6,Liberty Films,5,Excellent,80
17,119,AVATAR,Hollywood,2009,7.8,20th Century Fox,5,Normal,17
18,120,THE GODFATHER,Hollywood,1972,9.2,Paramount Pictures,5,Excellent,54
19,121,THE DARK KNIGHT,Hollywood,2008,9.0,Syncopy,5,Excellent,18
20,122,SCHINDLER'S LIST,Hollywood,1993,9.0,Universal Pictures,5,Excellent,33

In [88]:
df3 = movies.iloc[:7, 0:3]
df4 = movies.iloc[:4, 3:6]

In [89]:
df3

   movie_id                                        title   industry
1       102  DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS  Hollywood
2       103                        THOR: THE DARK WORLD   Hollywood
3       104                              THOR: RAGNAROK   Hollywood
4       105                      THOR: LOVE AND THUNDER   Hollywood
5       106                                       SHOLAY  Bollywood
6       107                  DILWALE DULHANIA LE JAYENGE  Bollywood
7       108                                     3 IDIOTS  Bollywood

In [90]:
df4

   year  rating          studio
1  2022     7.0  Marvel Studios
2  2013     6.8  Marvel Studios
3  2017     7.9  Marvel Studios
4  2022     6.8  Marvel Studios

In [91]:
pd.concat([df3,df4] ,axis = 1)       #match by using index

,movie_id,title,industry,year,rating,studio
1,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022.0,7.0,Marvel Studios
2,103,THOR: THE DARK WORLD,Hollywood,2013.0,6.8,Marvel Studios
3,104,THOR: RAGNAROK,Hollywood,2017.0,7.9,Marvel Studios
4,105,THOR: LOVE AND THUNDER,Hollywood,2022.0,6.8,Marvel Studios
5,106,SHOLAY,Bollywood,NaN,NaN,NaN
6,107,DILWALE DULHANIA LE JAYENGE,Bollywood,NaN,NaN,NaN
7,108,3 IDIOTS,Bollywood,NaN,NaN,NaN

In [92]:
df3.join(df4)

,movie_id,title,industry,year,rating,studio
1,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022.0,7.0,Marvel Studios
2,103,THOR: THE DARK WORLD,Hollywood,2013.0,6.8,Marvel Studios
3,104,THOR: RAGNAROK,Hollywood,2017.0,7.9,Marvel Studios
4,105,THOR: LOVE AND THUNDER,Hollywood,2022.0,6.8,Marvel Studios
5,106,SHOLAY,Bollywood,NaN,NaN,NaN
6,107,DILWALE DULHANIA LE JAYENGE,Bollywood,NaN,NaN,NaN
7,108,3 IDIOTS,Bollywood,NaN,NaN,NaN

In [93]:
df3.join(df4, how = "left")

,movie_id,title,industry,year,rating,studio
1,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022.0,7.0,Marvel Studios
2,103,THOR: THE DARK WORLD,Hollywood,2013.0,6.8,Marvel Studios
3,104,THOR: RAGNAROK,Hollywood,2017.0,7.9,Marvel Studios
4,105,THOR: LOVE AND THUNDER,Hollywood,2022.0,6.8,Marvel Studios
5,106,SHOLAY,Bollywood,NaN,NaN,NaN
6,107,DILWALE DULHANIA LE JAYENGE,Bollywood,NaN,NaN,NaN
7,108,3 IDIOTS,Bollywood,NaN,NaN,NaN

In [94]:
df3.join(df4, how = "right")

,movie_id,title,industry,year,rating,studio
1,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022,7.0,Marvel Studios
2,103,THOR: THE DARK WORLD,Hollywood,2013,6.8,Marvel Studios
3,104,THOR: RAGNAROK,Hollywood,2017,7.9,Marvel Studios
4,105,THOR: LOVE AND THUNDER,Hollywood,2022,6.8,Marvel Studios

In [95]:
df3.join(df4, how = "inner")  #only the match values shows by using index

,movie_id,title,industry,year,rating,studio
1,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022,7.0,Marvel Studios
2,103,THOR: THE DARK WORLD,Hollywood,2013,6.8,Marvel Studios
3,104,THOR: RAGNAROK,Hollywood,2017,7.9,Marvel Studios
4,105,THOR: LOVE AND THUNDER,Hollywood,2022,6.8,Marvel Studios

In [96]:
movies_data.to_excel("movie_analysis.xlsx",index = False)